### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by brandonmcconnell** [Jaaneek/t3-supabase-app-router#3]
Thanks for putting together this repo! This is the exact stack I was looking for.

I just ran into some issues when first installing the deps:

<details><summary>Source (text)</summary>

```
pnpm install
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Packages: +572
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/brandon.mcconnell/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext: Running postinstall script, done in 74ms
node_modules/.pnpm/@prisma+engines@4.16.2/node_modules/@prisma/engines: Running postinstall script, done in 174ms
node_modules/.pnpm/bufferutil@4.0.7/node_modules/bufferutil: Running install script, done in 1s
node_modules/.pnpm/utf-8-validate@5.0.10/node_modules/utf-8-validate: Running install script, done in 1.1s
Progress: resolved 580, reused 481, downloaded 91, added 572, done
node_modules/.pnpm/prisma@4.16.2/node_modules/prisma: Running preinstall script, done in 60ms
node_modules/.pnpm/@prisma+client@4.16.2_prisma@4.16.2/node_modules/@prisma/client: Running postinstall script, done in 516ms

> t3-app-dir-supabase@0.1.0 postinstall /Users/brandon.mcconnell/Projects/XXXXXX
> prisma generate

Prisma schema loaded from prisma/schema.prisma
Error:
You don't have any models defined in your schema.prisma, so nothing will be generated.
You can define a model like this:

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

More information in our documentation:
https://pris.ly/d/prisma-schema

 ELIFECYCLE  Command failed with exit code 1.
```

</details> 

![](https://github.com/Jaaneek/t3-supabase-app-router/assets/5913254/57e2883c-d529-4ce1-99f8-f9a565beea87)

**Comment by Jaaneek** [comment]
Hi @brandonmcconnell ,
Did you follow the next steps? This error is only because of prisma generate, you will rerun the prisma generate later on. The scripts are installed correctly from what I can see

**Comment by brandonmcconnell** [comment]
@Jaaneek Thanks!

Btw I'm getting some more errors. I'm installing `supabase` globally. It might be helpful to include that in the instructions for anyone who doesn't use it yet.

**Comment by brandonmcconnell** [comment]
@Jaaneek I run into this issue on the next step:

<img width="1084" alt="258543007-b82bdbe6-2034-4000-a1a1-a1c70fbe6f5c" src="https://github.com/Jaaneek/t3-supabase-app-router/assets/5913254/b0290317-1b27-4e4d-a323-d8215a80fb15">


I tried installing Supabase globally using `yarn global add supabase` but that produced this error:

```
yarn global add supabase
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/brandon.mcconnell/.config/yarn/global/node_modules/supabase: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments:
Directory: /Users/brandon.mcconnell/.config/yarn/global/node_modules/supabase
Output:
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
Installing Supabase CLI as a global module is not supported.
Please use one of the supported package managers: https://github.com/supabase/cli#install-the-cli

(Use `node --trace-uncaught ...` to show where the exception was thrown)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by brandonmcconnell** [comment]
@Jaaneek I run into this issue on the next step:

<img width="1088" alt="Screenshot 2023-08-04 at 6 50 03 PM" src="https://github.com/Jaaneek/t3-supabase-app-router/assets/5913254/22595a33-5691-47a4-b148-be56ca418742">

I tried installing Supabase globally using `yarn global add supabase` but that produced this error:

```
yarn global add supabase
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/brandon.mcconnell/.config/yarn/global/node_modules/supabase: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments:
Directory: /Users/brandon.mcconnell/.config/yarn/global/node_modules/supabase
Output:
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
Installing Supabase CLI as a global module is not supported.
Please use one of the supported package managers: https://github.com/supabase/cli#install-the-cli

(Use `node --trace-uncaught ...` to show where the exception was thrown)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by Jaaneek** [comment]
@brandonmcconnell here are instructions on how to install supabase CLI https://github.com/supabase/cli#getting-started

**Comment by brandonmcconnell** [comment]
> @brandonmcconnell here are instructions on how to install supabase CLI https://github.com/supabase/cli#getting-started

It's interesting that it can't be installed globally. So where should this be installed as a dev dependency? The project directory? Would it then make sense to include it in the `package.json` file?

**Comment by Jaaneek** [comment]
It could/should be installed globally
Homebrew example:
```
brew install supabase/tap/supabase
```

**Comment by brandonmcconnell** [comment]
Looks like the combination of installing supabase as a dev dep and via brew did the trick for that step.

After that, I ran `supabase init` with "VS Code workspace settings"

<img src="https://github.com/Jaaneek/t3-supabase-app-router/assets/5913254/2cd2f831-1ce9-4556-af40-76e2a579eb56" width="419">

Then, `yarn prepare:local` errored that `supabase start is not running`, so I ran `supabase start` and got this error:

```
supabase start --debug

Supabase CLI 1.82.6
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  in github.com/supabase/cli/internal/utils.AssertDockerIsRunning:50
  in github.com/supabase/cli/internal/start.Run:35
```

Any idea what I should do next? If you have some availability, I'd love to get on a call to walk through this, if you'd be available. This is my first time setting up Supabase, and I'm not sure exactly where I'm going wrong. I set up an Access Token in a new Supabase org, but I'm not sure what all should to fill these `.env` values with:

```
DIRECT_URL=
DATABASE_URL=

NEXT_PUBLIC_SUPABASE_PROJECT_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
NEXT_PUBLIC_SUPABASE_SERVICE_KEY=
NEXT_PUBLIC_SELF_HOSTING=0
```

**Comment by Jaaneek** [comment]
Yeah let's make a call, I will follow up on twitter
If someone has a similar problem:
After you run supabase start, the CLI will output all the data you need for envs in the console, if you develop it on remote then you have all the data in official supabase admin dashboard

**Comment by brandonmcconnell** [comment]
Thanks!

I tried using `supabase login` per the CLI instructions, and this is how that went:

<img width="1084" alt="" src="https://github.com/Jaaneek/t3-supabase-app-router/assets/5913254/149b5747-f62f-4664-a389-dd251402ef04">


After supplying my access token, I got this error:

```
yarn prepare:remote
yarn run v1.22.19
$ yarn update-types-remote && yarn prisma db pull && yarn prisma generate && yarn prisma-case-format --file prisma/schema.prisma  && yarn prisma generate
$ supabase gen types typescript --project-id "PUT YOUR SUPABASE REMOTE API KEY" --schema public > src/server/supabaseTypes.ts
failed to retrieve generated types: {"message":"Forbidden resource"}
Try rerunning the command with --debug to troubleshoot the error.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brandonmcconnell** [comment]
A call would be great — thanks!

I'll follow up on Twitter as well.

**Comment by Jaaneek** [comment]
supabase gen types typescript --project-id `"PUT YOUR SUPABASE REMOTE API KEY"` --schema public > src/server/supabaseTypes.ts

> PUT YOUR SUPABASE REMOTE API KEY

If you are gonna use remote database (hosted by supabase) you need to provide your supabase api key,

**Comment by brandonmcconnell** [comment]
@Jaaneek and that API key is different from the Access Token? Should I run that command as the CLI response suggests?

**Comment by Jaaneek** [comment]
Everything works smooth after our call, I will try to update readme to make the process easier to understand

**Comment by brandonmcconnell** [comment]
Thanks for your help!
